apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  kind: ClusterRole
  name: datadog-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: default
